/**
 * Danfoss TetTask Service API
 * Test Task
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CounterMeter = 'AllValues' | 'MaxValues' | 'MinValues';

export const CounterMeter = {
    AllValues: 'AllValues' as CounterMeter,
    MaxValues: 'MaxValues' as CounterMeter,
    MinValues: 'MinValues' as CounterMeter
};