/**
 * Danfoss TetTask Service API
 * Test Task
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CounterMeter = 0 | 1;

export const CounterMeter = {
    NUMBER_0: 0 as CounterMeter,
    NUMBER_1: 1 as CounterMeter
};