/**
 * Danfoss TetTask Service API
 * Test Task
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelObject } from './modelObject';

export interface ProblemDetails extends null<String, ModelObject> { 
  [key: string]: ModelObject;


}