/**
 * Danfoss TetTask Service API
 * Test Task
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Counter } from '../model/counter';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CounterService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Добавить показания счетчика
     * 
     * @param houseId идентификатор дома
     * @param value значение счетчика
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCounterByhouseGet(houseId: number, value: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public apiCounterByhouseGet(houseId: number, value: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public apiCounterByhouseGet(houseId: number, value: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public apiCounterByhouseGet(houseId: number, value: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (houseId === null || houseId === undefined) {
            throw new Error('Required parameter houseId was null or undefined when calling apiCounterByhouseGet.');
        }

        if (value === null || value === undefined) {
            throw new Error('Required parameter value was null or undefined when calling apiCounterByhouseGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (houseId !== undefined && houseId !== null) {
            queryParameters = queryParameters.set('houseId', <any>houseId);
        }
        if (value !== undefined && value !== null) {
            queryParameters = queryParameters.set('value', <any>value);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('get',`${this.basePath}/api/Counter/byhouse`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Добавить показания счетчика
     * 
     * @param serialNumber серийный номер счетчика
     * @param value значение счетчика
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCounterByserialnumberGet(serialNumber: string, value: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public apiCounterByserialnumberGet(serialNumber: string, value: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public apiCounterByserialnumberGet(serialNumber: string, value: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public apiCounterByserialnumberGet(serialNumber: string, value: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (serialNumber === null || serialNumber === undefined) {
            throw new Error('Required parameter serialNumber was null or undefined when calling apiCounterByserialnumberGet.');
        }

        if (value === null || value === undefined) {
            throw new Error('Required parameter value was null or undefined when calling apiCounterByserialnumberGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (serialNumber !== undefined && serialNumber !== null) {
            queryParameters = queryParameters.set('serialNumber', <any>serialNumber);
        }
        if (value !== undefined && value !== null) {
            queryParameters = queryParameters.set('value', <any>value);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('get',`${this.basePath}/api/Counter/byserialnumber`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Добавить новый счетчик
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCounterPost(body?: Counter, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public apiCounterPost(body?: Counter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public apiCounterPost(body?: Counter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public apiCounterPost(body?: Counter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<number>('post',`${this.basePath}/api/Counter`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
